language: cpp
compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  # Currently inside the cloned repo path.
  # Install libespm.
  - git clone https://github.com/WrinklyNinja/libespm.git ../libespm
  # Install Boost & Google Test
  - sudo apt-get install -y libboost-filesystem1.48-dev libboost-locale1.48-dev libboost-iostreams1.48-dev
  # Install Google Test
  - cd ..
  - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
  - unzip gtest-1.7.0.zip
  - cd gtest-1.7.0
  - cmake .
  - make
  # Move back into the cloned libloadorder repo path.
  - cd $TRAVIS_BUILD_DIR

before_script:
  - mkdir build
  - cd build
  # Fetch plugins to test with.
  - wget https://github.com/WrinklyNinja/testing-plugins/archive/master.zip
  - unzip master.zip
  # Travis machines are 64 bit, and the deps use dynamic linking.
  - cmake .. -DPROJECT_ARCH=64 -DPROJECT_STATIC_RUNTIME=OFF -DGTEST_ROOT=../gtest-1.7.0

script: make && ./libloadorder-tester
