sudo: false
language: cpp
compiler:
  - gcc

# Need Boost 1.54+, which isn't in the 12.04 repositories, and GCC 5 - install
# from a PPA.
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost-filesystem1.55-dev
      - libboost-locale1.55-dev
      - gcc-5
      - g++-5

install:
  # Use GCC 5.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  # Currently inside the cloned repo path.
  - cd ..
  # Install libespm.
  - wget https://github.com/WrinklyNinja/libespm/archive/2.2.0.tar.gz -O - | tar -xz
  - mv libespm-2.2.0 libespm
  # Install Google Test
  - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz -O - | tar -xz
  - cd googletest-release-1.7.0
  - cmake .
  - make
  # Move back into the cloned libloadorder repo path.
  - cd $TRAVIS_BUILD_DIR

before_script:
  - mkdir build
  - cd build
  # Fetch plugins to test with.
  - wget https://github.com/WrinklyNinja/testing-plugins/archive/master.tar.gz -O - | tar -xz
  - mv testing-plugins-master/* ./
  # Travis machines are 64 bit, and the deps use dynamic linking.
  - cmake .. -DPROJECT_ARCH=64 -DPROJECT_STATIC_RUNTIME=OFF -DGTEST_ROOT=../googletest-release-1.7.0

script: make && ./tests
